server:
  port: 5000
  servlet:
    context-path: "/"

management:
  endpoint:
    health:
      show-components: ALWAYS
      show-details: ALWAYS
    service-registry:
      enabled: false
  metrics:
    export:
      prometheus:
        descriptions: false
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: [ "info", "health", "prometheus" ]
      path-mapping:
        prometheus: "metrics"

springdoc:
  api-docs:
    path: /winwine/web-app/documents/v1/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /winwine/web-app/documents/v1
    
http:
  api:
    prefix: /winwine/web-app/apis/v1

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 2
      maximumPoolSize: 8
    partitionEnabled: true
    driver-class-name: org.mariadb.jdbc.Driver

    url: jdbc:mariadb://zoy-winwine-dev.ccauvd1rzgyv.ap-southeast-1.rds.amazonaws.com:3306/winwine_webapp?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor
    username: admin
    password: DBPassword

common:
  appEnv: QC